name: decryptM
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.0.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=1.0.3
  - python=3.6.12
  - scipy=1.1.0
  - seaborn=0.9.0
  - statsmodels=0.11.1
  - toml=0.10.1
  - tqdm=4.36.1